import json
from pathlib import Path

content = {
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os, sys, subprocess, gc, traceback, torch\n",
    "from pathlib import Path\n",
    "import soundfile as sf\n",
    "import numpy as np\n",
    "from datetime import datetime\n",
    "import warnings\n",
    "\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "# Setup logging to file so kaggle-gpu-connector can fetch it in real-time\n",
    "def log(msg): \n",
    "    ts = datetime.now().strftime('%H:%M:%S')\n",
    "    line = f\"[{ts}] {msg}\"\n",
    "    print(line, flush=True)\n",
    "    with open(\"kaggle_remote.log\", \"a\") as f:\n",
    "        f.write(line + \"\\n\")\n",
    "\n",
    "# 1. Setup - Targeted FAST installation\n",
    "log(\"Checking environment...\")\n",
    "try:\n",
    "    if subprocess.run(\"sox --version\", shell=True, capture_output=True).returncode != 0:\n",
    "        log(\"Installing system sox and upgrading transformers...\")\n",
    "        subprocess.run(\"apt-get update -q && apt-get install -y -q sox libsox-fmt-all\", shell=True)\n",
    "        subprocess.run(\"pip install -q -U sox qwen-tts==0.1.1 'transformers>=4.48.0'\", shell=True)\n",
    "    else:\n",
    "        log(\"Sox already present. Ensuring python packages...\")\n",
    "        subprocess.run(\"pip install -q -U qwen-tts==0.1.1 'transformers>=4.48.0'\", shell=True)\n",
    "    \n",
    "    from qwen_tts import Qwen3TTSModel\n",
    "    log(\"Setup complete (Imports done).\")\n",
    "except Exception as e:\n",
    "    log(f\"Setup warning: {e}. Attempting recovery full install...\")\n",
    "    subprocess.run(\"pip install -q -U qwen-tts==0.1.1 sox 'transformers>=4.48.0' --no-cache-dir\", shell=True)\n",
    "    from qwen_tts import Qwen3TTSModel\n",
    "    log(\"Setup complete (Recovery Imports done).\")\n",
    "\n",
    "# 2. Parameters (Injected by JobManager)\n",
    "text = \"The GPU is faster. No more excuses. Successfully comparing CPU and GPU.\"\n",
    "voice = \"Ryan\"\n",
    "output_file = \"qwen.wav\"\n",
    "\n",
    "# 3. Model Loading & Verification\n",
    "log(f\"Loading Qwen model. Text: {text[:50]}...\")\n",
    "try:\n",
    "    # Use float32 for T4 stability (avoiding NaNs in multinomial)\n",
    "    model = Qwen3TTSModel.from_pretrained(\n",
    "        \"Qwen/Qwen3-TTS-12Hz-0.6B-CustomVoice\",\n",
    "        torch_dtype=torch.float32,\n",
    "        device_map=\"auto\" \n",
    "    )\n",
    "except Exception as e:\n",
    "    log(f\"Load failed: {e}. Retrying with float32 explicitly...\")\n",
    "    model = Qwen3TTSModel.from_pretrained(\n",
    "        \"Qwen/Qwen3-TTS-12Hz-0.6B-CustomVoice\",\n",
    "        torch_dtype=torch.float32,\n",
    "        device_map=\"auto\"\n",
    "    )\n",
    "\n",
    "# 4. Prompt Logic\n",
    "log(f\"Generating audio for voice: {voice}\")\n",
    "choices = {\n",
    "    \"Ryan\": (\"Ryan\", \"Ryan is a male voice...\"),\n",
    "}\n",
    "ref_text, ref_prompt = choices.get(voice, (\"Ryan\", \"Ryan voice\"))\n",
    "\n",
    "# 5. Synthesis block\n",
    "try:\n",
    "    log(\"Synthesizing...\")\n",
    "    with torch.inference_mode():\n",
    "        audio_array, sample_rate = model.generate_custom_voice(\n",
    "            text=text,\n",
    "            speaker=ref_text,\n",
    "            language=\"english\",\n",
    "            do_sample=False,\n",
    "            subtalker_dosample=False\n",
    "        )\n",
    "    \n",
    "    # 6. Saving (Proper Tensor handling)\n",
    "    if hasattr(audio_array, 'cpu'):\n",
    "        audio_array = audio_array.cpu().numpy()\n",
    "    \n",
    "    # Ensure it's 1D\n",
    "    if len(audio_array.shape) > 1:\n",
    "        audio_array = audio_array.flatten()\n",
    "\n",
    "    sf.write(output_file, audio_array, int(sample_rate))\n",
    "    log(f\"SUCCESS: Audio saved to {output_file}. Array shape: {audio_array.shape}\")\n",
    "except Exception as e:\n",
    "    log(f\"ERROR: Synthesis failed: {str(e)}\")\n",
    "    traceback.print_exc()\n",
    "\n",
    "# 7. Cleanup\n",
    "del model\n",
    "torch.cuda.empty_cache()\n",
    "gc.collect()\n",
    "log(\"Job complete.\")\n"
   ]
  }
 ],
 \"metadata\": {
  \"kernelspec\": {
   \"display_name\": \"Python 3\",
   \"language\": \"python\",
   \"name\": \"python3\"
  },
  \"language_info\": {
   \"name\": \"python\",
   \"version\": \"3.10.12\"
  }
 },
 \"nbformat\": 4,
 \"nbformat_minor\": 5
}

with open('src/voicegenhub/kaggle/notebooks/kaggle-qwen.ipynb', 'w') as f:
    json.dump(content, f, indent=1)
